apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend
  labels:
    app: {{ .Release.Name }}-backend
spec:
  ports:
  - port: {{ .Values.service.backend.port }}
    targetPort: 3000
    protocol: TCP
  selector:
    app: {{ .Release.Name }}-backend
  type: {{ .Values.service.backend.type }}
