version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    restart: unless-stopped
  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    restart: unless-stopped
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    restart: unless-stopped
