apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: custom-nginx
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/pxkundu/JenkinsTask.git
    targetRevision: feature/kube-helm-argocd
    path: helm-charts/custom-nginx
  destination:
    server: https://kubernetes.default.svc
    namespace: partha-app-ns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
