apiVersion: v2
name: custom-nginx
description: A Helm chart for deploying an Nginx web application
version: 0.1.0
appVersion: "1.25"
type: application
maintainers:
  - name: Partha Sarathi
    email: pxkundu2@shockers.wichita.edu
keywords:
  - nginx
  - webserver
  - learning
home: https://github.com/pxkundu/JenkinsTask
sources:
  - https://github.com/pxkundu/JenkinsTask/tree/feature/kube-helm-argocd/helm-charts/custom-nginx
