---
- name: Configure Log Rotation and CloudWatch Integration
  hosts: k8s_workers
  become: yes
  tasks:
    - name: Install logrotate
      ansible.builtin.yum:
        name: logrotate
        state: present

    - name: Configure logrotate for application logs
      ansible.builtin.copy:
        content: |
          /var/log/app/*.log {
              daily
              rotate 7
              compress
              missingok
              notifempty
              create 0644 ec2-user ec2-user
          }
        dest: /etc/logrotate.d/app
        mode: '0644'

    - name: Verify logrotate configuration
      ansible.builtin.command: logrotate -d /etc/logrotate.d/app
      register: logrotate_debug
      changed_when: false

    - name: Display logrotate debug
      ansible.builtin.debug:
        msg: "{{ logrotate_debug.stdout_lines | select('match', '.*rotating.*') | list }}"

    - name: Install CloudWatch Logs agent
      ansible.builtin.shell: |
        curl https://s3.amazonaws.com/aws-cloudwatch/downloads/latest/awslogs-agent-setup.py -O
        python3 awslogs-agent-setup.py --region us-east-1 --non-interactive \
          --config-file /tmp/awslogs.conf
        rm awslogs-agent-setup.py
      args:
        creates: /usr/local/bin/awslogs-agent

    - name: Configure CloudWatch Logs agent
      ansible.builtin.copy:
        content: |
          [general]
          state_file = /var/awslogs/state/agent-state
          [logstream]
          log_group_name = /eks/k8-worker-partha
          log_stream_name = {instance_id}/app
          file = /var/log/app/*.log
          datetime_format = %Y-%m-%d %H:%M:%S
          initial_position = start_of_file
        dest: /etc/awslogs/awslogs.conf
        mode: '0644'

    - name: Restart CloudWatch Logs agent
      ansible.builtin.service:
        name: awslogs
        state: restarted
