
    plugin: aws_ec2
    regions:
      - us-east-1  # Replace with your region
    filters:
      tag:k8s-role: worker  # Assumes k8-worker-partha has this tag
      instance-state-name: running
    keyed_groups:
      - key: tags.k8s-role
        prefix: k8s
        separator: "_"
    hostnames:
      - private-ip-address
    compose:
      ansible_user: "'ec2-user'"
      ansible_ssh_private_key_file: "'/home/ec2-user/.ssh/id_rsa_partha'"

