replicaCount: 1

frontend:
  image:
    repository: pxkundu/todo-frontend
    tag: "latest"
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: "0.1"
      memory: "128Mi"
    limits:
      cpu: "0.5"
      memory: "512Mi"

backend:
  image:
    repository: pxkundu/todo-backend
    tag: "latest"
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: "0.1"
      memory: "128Mi"
    limits:
      cpu: "0.5"
      memory: "512Mi"

service:
  frontend:
    type: ClusterIP  # Changed from NodePort
    port: 80
  backend:
    type: ClusterIP  # Changed from NodePort
    port: 3000

ingress:
  enabled: true
  ingressClassName: alb
  host: todo.example.com
  path: "/"
  pathType: Prefix

autoscaling:
  enabled: false  # Optional: Enable later for scaling demo
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
