name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: self-hosted  # Or [self-hosted, amazon-linux-2] if you added a specific label

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Docker (if not already installed on the EC2 instance)
      - name: Set up Docker
        run: |
          sudo yum install -y docker
          sudo service docker start
          sudo usermod -aG docker ec2-user  # Add ec2-user (or your user) to the docker group

      # Install Node.js and npm
      - name: Install Node.js
        run: |
          curl -sL https://rpm.nodesource.com/setup_16.x | sudo -E bash -
          sudo yum install -y nodejs

      # Install backend dependencies and run tests
      - name: Test Backend
        working-directory: ./backend
        run: |
          npm install

      # Install frontend dependencies and run tests
      - name: Test Frontend
        working-directory: ./frontend
        run: |
          npm install

      # Test the full stack with docker-compose
      - name: Test Docker Compose Stack
        run: |
          docker-compose down || true
          docker-compose up -d --build

    # Ensure containers are cleaned up even if the job fails
    env:
      COMPOSE_DOCKER_CLI_BUILD: 1
      DOCKER_BUILDKIT: 1
